CREATE TABLE PLAYER(
        PLAYER_ID INT PRIMARY KEY,
        PNAME VARCHAR(20),
        SPECIALITY VARCHAR(20),
        DATE_OF_JOINING DATE,
        NUM_MATCHES INT CHECK(NUM_MATCHES>=0),
        TEAM_ID INT,
        constraint TID FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID)
        );
		
CREATE TABLE TEAM(
		TEAM_ID INT PRIMARY KEY,
		TNAME VARCHAR(20),
		PLAYER_NUM INT CHECK(PLAYER_NUM=11)
		);
		
CREATE TABLE MATCHES(
		MATCH_ID INT PRIMARY KEY,
		TEAM1 INT,
		TEAM2 INT,
		MATCH_DATE DATE,
		WINNER VARCHAR(20),
		MAN_OF_THE_MATCH INT,
		constraint T1 FOREIGN KEY (TEAM1) REFERENCES TEAM(TEAM_ID),
		constraint T2 FOREIGN KEY (TEAM2) REFERENCES TEAM(TEAM_ID),
		constraint MOM FOREIGN KEY (MAN_OF_THE_MATCH) REFERENCES PLAYER(PLAYER_ID)
		);
		